### PR TITLE
Update milkrice

### PR DESCRIPTION
**Pull request by Krisopu**
I added cinnamon, that I initially forgot to write down in the recipe. I consider cinnamon as necessary for the taste

### CODE REVIEW

**Comment by Krisopu** [comment]
How do you like my xhange?

**Comment by Hermandez** [comment]
Is it okay now?

**Comment by Hermandez** [comment]
Cool!!!

**Comment by Krisopu** [comment]
Did you already accepted the change or did I just onesided initiated the merging process?

**Comment by Hermandez** [comment]
It is merged already. But I didn't initiate it!

**Pull request merged**
